### ISSUE TITLE
Footer of the website 

### ISSUE THREAD

**Issue by SriSatyaT** [2024-SANDHYA/Blood-Buddy#1]
![BLOOD BUDDY - Google Chrome 15-09-2021 14_29_31_LI](https://user-images.githubusercontent.com/78905067/133403981-d9284db2-0477-49e0-a169-7cc9213b62fe.jpg)
will try to arrange the content and social media links properly

**Comment by 2024-SANDHYA** [comment]
> 
> 
> ![BLOOD BUDDY - Google Chrome 15-09-2021 14_29_31_LI](https://user-images.githubusercontent.com/78905067/133403981-d9284db2-0477-49e0-a169-7cc9213b62fe.jpg)
> will try to arrange the content and social media links properly

Go ahead !!

**Comment by davyj123** [comment]
@SriSatyaT could you please assign this task to me.

**Comment by SriSatyaT** [comment]
> @SriSatyaT could you please assign this task to me. I can redesign this properly.

You can work on it if you want to. But the maintainer of this repo need to assign to you.

**Comment by Starkl7** [comment]
I wanted to work on this as part of SWOC'21.
How do you want this to be rearranged?

**Comment by prachigarg19** [comment]
I'd like to work on this. I can make this a responsive footer. I'd be happy to help, please assign it to me.

**Comment by 2024-SANDHYA** [comment]
You can take inspiration from dribble or Behance and show your creativity.  :)

**Comment by davyj123** [comment]
could you please assign this task to me. I will design fully reponsive footer for this.

**Comment by MukadamSuha** [comment]
Please assign me this issue, would like to work on it.

**Comment by tiasaxena** [comment]
![footer](https://user-images.githubusercontent.com/89907755/145788058-32010f6e-0c36-4b96-8ce8-eeb3e568f899.png)


Hey! I want to redesign the footer. I can make a responsive one while making sure the important stuff must be eye-catchy enough. Can I be assigned this😇? I'll be happy to contribute!

**Comment by tiasaxena** [comment]
@2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
@Starkl7  More than 12 days no update? Please let me know in next 24 hrs or I'll have to assign it to someone else.

**Comment by 2024-SANDHYA** [comment]
Are you willing to work on thiS?  The one who'll respond first, I'll assign to him/her @MukadamSuha @prachigarg19 @SriSatyaT @davyj123

**Comment by Yash-RajSingh** [comment]
> Are you willing to work on thiS? The one who'll respond first, I'll assign to him/her @MukadamSuha @prachigarg19 @SriSatyaT @davyj123

I can work on this if it's ok

**Comment by MukadamSuha** [comment]
> Are you willing to work on thiS? The one who'll respond first, I'll assign to him/her @MukadamSuha @prachigarg19 @SriSatyaT @davyj123

I will work on it.

**Comment by davyj123** [comment]
I am ready to work with collaboration also.

**Comment by 2024-SANDHYA** [comment]
What's the working status @MukadamSuha

**Comment by MukadamSuha** [comment]
Almost Done will PR it now
