### ISSUE TITLE
Linking different pages to the HomePage

### ISSUE THREAD

**Issue by tiasaxena** [2024-SANDHYA/Blood-Buddy#108]
Each of the links when clicked opens up in a new tab and the client looses access to the first / landing page. Plus, lots of tabs pile up. I think limiting to one page will be better and at the same time providing the link to the home page on each of the different links, will be rather better. Please assign me the task, @2024-SANDHYA, if 😀

**Comment by 2024-SANDHYA** [comment]
Every page has the link to the home page, I don't want to change the rest. @tiasaxena
