### ISSUE TITLE
Issue in Header

### ISSUE THREAD

**Issue by rohan-singh987** [2024-SANDHYA/Blood-Buddy#11]
Hey! I think you need to change some CSS in Your header as you nav-bar is too low. it should be at the top of website

**Comment by rohan-singh987** [comment]
assign it to me, I will love to resolve this issue

**Comment by pragyaSingh13** [comment]
I have fixed the header issue and made some minor customizations accordingl
<img width="700" alt="ssgit" src="https://user-images.githubusercontent.com/85486989/133918865-de0023fb-9792-48b9-a40c-2d18959dd52a.png">
y.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> I have fixed the header issue and made some minor customizations accordingly and other minor issues on the page
> <img alt="ssgit" width="700" src="https://user-images.githubusercontent.com/85486989/133918865-de0023fb-9792-48b9-a40c-2d18959dd52a.png">
> y.

Doesn't look good to me , you can customize the navbar in the original way it was & you've also changed the order of links too. About us should come first then volunteer and so on.

**Comment by pragyaSingh13** [comment]
Alright, no issues I'll fix it

**Comment by copyNinja1219** [comment]
can you describe the issue please ?
