### ISSUE TITLE
Updating Document : Correction of Spelling Mistakes in the ReadMe

### ISSUE THREAD

**Issue by Kunal0220** [2024-SANDHYA/Blood-Buddy#121]
There is a spelling mistake in the Readme ( Point number 6 I guess) , We should resolve it ASAP .

**Comment by SupriyaKumari08** [comment]
Hey @Kunal0220 , can I work on this issue?

**Comment by Kunal0220** [comment]
Hey @SupriyaKumari08 , I don't have the permission to assign it to you , @2024-SANDHYA can you please assign this to her ?

**Comment by 2024-SANDHYA** [comment]
Only code contributions are being counted not Readme. @Kunal0220
