### ISSUE TITLE
Enhancement of the About Us Section

### ISSUE THREAD

**Issue by impranavtg** [2024-SANDHYA/Blood-Buddy#123]
I want to modify the About us Section using CSS grid and make it responsive for all devices. Also, I want to add a greyish color to the background of about us cards so that the box-shadow would look more attractive and the card would appear to be floating on the background. for your reference, I am adding a photo of my project. 
Will you Assign this to me
![screenshot-impranavtg github io-2022 01 16-21_20_03](https://user-images.githubusercontent.com/83161133/149667187-b6493bc4-977f-4c08-ab9c-f148b9282cf9.png)
?

**Comment by 2024-SANDHYA** [comment]
Issue already exists @impranavtg   #7

**Comment by impranavtg** [comment]
Could you suggest an issue on which I could contribute?
It would be really appreciated.
Regards

**Comment by 2024-SANDHYA** [comment]
Issues with the tag "up for grab" select those @impranavtg

**Comment by impranavtg** [comment]
There is no issue having this tag.

**Comment by 2024-SANDHYA** [comment]
> There is no issue having this tag.

Then all are assigned, create an issue you want to work on then. @impranavtg
