### ISSUE TITLE
Height of cards under About Us section not consistent

### ISSUE THREAD

**Issue by SupriyaKumari08** [2024-SANDHYA/Blood-Buddy#125]
Innovate card's height isn't consistent with adjacent cards, hence hindering the UI of the page. I can fix this issue. @2024-SANDHYA Can you assign this to me?
<img width="811" alt="Blood-buddy" src="https://user-images.githubusercontent.com/84588360/149719415-892d6b8d-1bd4-44ad-8682-2f6e09125fba.PNG">

**Comment by 2024-SANDHYA** [comment]
Create the PR within 10 days, @SupriyaKumari08
