### ISSUE TITLE
Volunteer page alignment

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#130]
Align all the points properly. Right now it is like :

![image](https://user-images.githubusercontent.com/75671152/151670050-3d4df1b8-a6b5-4769-ab08-609144bc3af5.png)

**Comment by YarinLevi5** [comment]
Do you mean align the icons? that they will be on the right side?

**Comment by impranavtg** [comment]
Hey, @2024-SANDHYA I can work on this issue. Provide me with some more details about your requirements plus I want to fix the button link on this page. Because if the user is clicking on any button on this page. The home page loads up. Instead of a specific section of that page. I mean if the user is clicking on the about us button then it should redirect to the about us section on the home page. I would fix that.

**Comment by 2024-SANDHYA** [comment]
@impranavtg  @YarinLevi5  All the information is provided clearly, alignment needs to be fixed towards the left as can be seen in the image provided.

**Comment by MThabsheer7** [comment]
Hey, @2024-SANDHYA , is the issue under work? or I can work on it.

**Comment by impranavtg** [comment]
> @impranavtg @YarinLevi5 All the information is provided clearly, alignment needs to be fixed towards the left as can be seen in the image provided.

Okay I understood. Can you assign this issue to me. So that I could start working on it.
Regards

**Comment by 2024-SANDHYA** [comment]
> > @impranavtg @YarinLevi5 All the information is provided clearly, alignment needs to be fixed towards the left as can be seen in the image provided.
> 
> Okay I understood. Can you assign this issue to me. So that I could start working on it. Regards

Okay @impranavtg make sure to create a PR within next 5 days, or I have to unassign you this issue.

**Comment by impranavtg** [comment]
> > > @impranavtg @YarinLevi5 All the information is provided clearly, alignment needs to be fixed towards the left as can be seen in the image provided.
> > 
> > 
> > Okay I understood. Can you assign this issue to me. So that I could start working on it. Regards
> 
> Okay @impranavtg make sure to create a PR within next 5 days, or I have to unassign you this issue.

Okay I'll make sure that.
