### ISSUE TITLE
we can add colourfull heading 

### ISSUE THREAD

**Issue by DPR-4** [2024-SANDHYA/Blood-Buddy#135]
Add colorful heading to the "what is all about this" and "Our super heroes" and also provide some cool effects

## Thank you for your contribution to Bloody-Buddy 🤩🤩 

[![GitHub license](https://img.shields.io/badge/license-MIT-blue.svg)](LICENSE) ![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)  ![PRs Welcome](https://img.shields.io/badge/PRs-welcome-green.svg)

**Please mention the following in order to get PR merged**  🙌🏻🙌🏻 

1. Kind of change this PR introduce : Add colorful heading
2. Issue it resolves : heading look more attractive than previous  
3. Screenshots & GitHub Page Link : https://github.com/DPR-4/Blood-Buddy
 here is screenshot 
![Screenshot (357)](https://user-images.githubusercontent.com/94070396/155153649-b39de142-a0ea-4960-ace3-56a15f69a558.png)
![Screenshot (358)](https://user-images.githubusercontent.com/94070396/155153733-8f45bd23-1b8c-48b3-943c-0ec64b6439e1.png)
![Screenshot (359)](https://user-images.githubusercontent.com/94070396/155153784-2e73ec29-b444-40e3-a618-a03cd4b27b86.png)
![Screenshot (360)](https://user-images.githubusercontent.com/94070396/155153807-262bb009-7f24-4ec1-bc79-9331111a2aac.png)

**Comment by 2024-SANDHYA** [comment]
Under issue, you cannot create a PR. @DPR-4

**Comment by DPR-4** [comment]
sorry by mistake it happened
