### ISSUE TITLE
Add footer in all connected web-pages.

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#17]

**Comment by aniket-1812** [comment]
I would like to work on this... Can you explain how do you want me to style it?

**Comment by 2024-SANDHYA** [comment]
> I would like to work on this... Can you explain how do you want me to style it? SWOC'21

Add the existing footer in all the web pages.

**Comment by artimanputra** [comment]
Hey there, I would like to work on this issue

**Comment by 2024-SANDHYA** [comment]
> Hey there, I would like to work on this issue

Already assigned to @aniket-1812

**Comment by aniket-1812** [comment]
Hii @2024-SANDHYA .... Already made my PR. Can you suggest any other changes you want me to make or It's all ok ?
