### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#2]
Make the website fully responsive.

**Comment by irsayvid** [comment]
I would like to work on this and fix the text-overflow issue in mobile view

**Comment by 2024-SANDHYA** [comment]
> 
> 
> I would like to work on this and fix the text-overflow issue in mobile view

Assigned !!

**Comment by Anushh23** [comment]
Hey! I would like to work on this issue and make the site completely responsive.

**Comment by irsayvid** [comment]
Hey @Anushh23 ! Go ahead with it. Initially, I thought of working on this issue but currently I'm equipped with other things.

**Comment by Anushh23** [comment]
> Hey @Anushh23 ! Go ahead with it. Initially, I thought of working on this issue but currently I'm equipped with other things.

Thanks a lot!

**Comment by 7ORP3DO** [comment]
_Hey @2024-SANDHYA can i work on this issue?_
