### ISSUE TITLE
Making a new sticky navbar

### ISSUE THREAD

**Issue by SushantPatial** [2024-SANDHYA/Blood-Buddy#25]
I'll make a new appealing navbar for the website.

**Comment by 2024-SANDHYA** [comment]
> I'll make a new appealing navbar for the website.

Can you share any design you have in mind @SushantPatial

**Comment by SushantPatial** [comment]
Something like this with a bigger font

![image](https://user-images.githubusercontent.com/84243683/144437932-ebc5d7b6-7626-4988-b307-c0ac9a8bb9aa.png)

**Comment by Pushti-R** [comment]
i want to work

**Comment by 2024-SANDHYA** [comment]
> Something like this with a bigger font
> 
> ![image](https://user-images.githubusercontent.com/84243683/144437932-ebc5d7b6-7626-4988-b307-c0ac9a8bb9aa.png)
> 
> Will also add a background to the navbar as you scroll down the hero

Okay, go ahead! :)  @SushantPatial
