### ISSUE TITLE
Design logo for the website

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#3]

**Comment by Yashesvinee** [comment]
![ed9d1d19f0c842109becb67d6f6586b2](https://user-images.githubusercontent.com/76458668/133558355-ab2600cc-53f2-4a4e-b3bd-712a95f1d3ce.png)
Hi Here's a quick idea for the logo. Is it okay?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> ![ed9d1d19f0c842109becb67d6f6586b2](https://user-images.githubusercontent.com/76458668/133558355-ab2600cc-53f2-4a4e-b3bd-712a95f1d3ce.png)
> Hi Here's a quick idea for the logo. Is it okay?

Looks good to me !!

**Comment by 2024-SANDHYA** [comment]
> 
> 
> ![ed9d1d19f0c842109becb67d6f6586b2](https://user-images.githubusercontent.com/76458668/133558355-ab2600cc-53f2-4a4e-b3bd-712a95f1d3ce.png)
> Hi Here's a quick idea for the logo. Is it okay?

Hey, check the site now, the logo is way too large you can fix the size too though !

**Comment by Palak-2109** [comment]
![image](https://user-images.githubusercontent.com/76587145/144377368-c269cc19-e06e-4627-ba52-099f7a6270a5.png)
how's this..
