### ISSUE TITLE
updating register page 

### ISSUE THREAD

**Issue by leesha19** [2024-SANDHYA/Blood-Buddy#32]
Register page has a password strength meter which is not working properly i would like to change and style it + there is no show password available for user and also there is no footer on register page @2024-SANDHYA

**Comment by leesha19** [comment]
@2024-SANDHYA could you please assign it to me i already started working on it

**Comment by 2024-SANDHYA** [comment]
> Register page has a password strength meter which is not working properly i would like to change and style it + there is no show password available for user and also there is no footer on register page @2024-SANDHYA

The issue already exists #34

**Comment by leesha19** [comment]
> > Register page has a password strength meter which is not working properly i would like to change and style it + there is no show password available for user and also there is no footer on register page @2024-SANDHYA
> 
> The issue already exists #34

but i raised it 5 hours ago and issue #34 was raised 3 hours ago so why you closed my issue . It should be assigned to me and not him

**Comment by 2024-SANDHYA** [comment]
> > > Register page has a password strength meter which is not working properly i would like to change and style it + there is no show password available for user and also there is no footer on register page @2024-SANDHYA
> > 
> > 
> > The issue already exists #34
> 
> but i raised it 5 hours ago and issue #34 was raised 3 hours ago so why you closed my issue . It should be assigned to me and not him

I saw that one first. Anyways fine you too can work on this and whosoever will make the PR first, I'll merge that.

**Comment by davyj123** [comment]
Could you assign this task to me.
