### ISSUE TITLE
register buttons hover

### ISSUE THREAD

**Issue by geetika005** [2024-SANDHYA/Blood-Buddy#47]
will add a hover effect to the buttons of register form
please assign it to me

**Comment by 4bhishek10** [comment]
can I add hover effect to buttons?

**Comment by geetika005** [comment]
I have already added it and added made a pr for it

**Comment by 2024-SANDHYA** [comment]
> can I add hover effect to buttons?

Stop commenting on each and every issue, which is already assigned. @4bhishek10  It's on FCFS basis
