### ISSUE TITLE
Create a "login form" for blood doners

### ISSUE THREAD

**Issue by anmol20112000** [2024-SANDHYA/Blood-Buddy#49]
I will create a login form for blood doners  so that they can register on the website.plzzz assign this work to me. Suggest some ideas on this..@2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
> I will create a login form for blood doners so that they can register on the website.plzzz assign this work to me. Suggest some ideas on this..@2024-SANDHYA

Already informed you not to create issues, it'll be done by mentors ONLY. Drop your idea in discord channel of the project
