### ISSUE TITLE
get help page styling

### ISSUE THREAD

**Issue by leesha19** [2024-SANDHYA/Blood-Buddy#57]
hey there i would like to do some changes on get help page as the background color of place holder is default which is grey ,and the send button is also not properly styled i want to change it according to theme color which is blue
![image](https://user-images.githubusercontent.com/88451246/145814937-7431935f-9d6c-4232-83f6-1bd725f90a7c.png)

**Comment by 2024-SANDHYA** [comment]
@leesha19  Issue already exists #5  If the assigned person didn't respond in 24hrs, I'll assign it to you.

**Comment by leesha19** [comment]
> @leesha19 Issue already exists #5 If the assigned person didn't respond in 24hrs, I'll assign it to you.

ok

**Comment by leesha19** [comment]
> @leesha19 Issue already exists #5 If the assigned person didn't respond in 24hrs, I'll assign it to you.

hey as 24 hrs completed can i work on this now
