### ISSUE TITLE
Donate page is not responsive

### ISSUE THREAD

**Issue by 7ORP3DO** [2024-SANDHYA/Blood-Buddy#68]
Hey [Danate Page](https://2024-sandhya.github.io/Blood-Buddy/donate.html) is not reponsive. 

### On Mobile (425 x 760px) : 
![2024-sandhya github io_Blood-Buddy_donate html (1)](https://user-images.githubusercontent.com/80192140/146161659-dfb9b609-c898-4416-8703-9729321c6da5.png)

### On Tablet (768x 1024px) : 
![2024-sandhya github io_Blood-Buddy_donate html (2)](https://user-images.githubusercontent.com/80192140/146162346-279dc563-329b-4c0a-8b3f-a23106fc3c54.png)

**Comment by 2024-SANDHYA** [comment]
> Hey [Danate Page](https://2024-sandhya.github.io/Blood-Buddy/donate.html) is not reponsive.
> ### On Mobile (425 x 760px) :
> 
> ![2024-sandhya github io_Blood-Buddy_donate html (1)](https://user-images.githubusercontent.com/80192140/146161659-dfb9b609-c898-4416-8703-9729321c6da5.png)
> ### On Tablet (768x 1024px) :
> 
> ![2024-sandhya github io_Blood-Buddy_donate html (2)](https://user-images.githubusercontent.com/80192140/146162346-279dc563-329b-4c0a-8b3f-a23106fc3c54.png)

The issue already exists #2
