### ISSUE TITLE
Review Section

### ISSUE THREAD

**Issue by Sanjanabharadwaj25** [2024-SANDHYA/Blood-Buddy#70]
It contains the user reviews. It can also have the option for a user to leave a review.

**Comment by tiasaxena** [comment]
hey @2024-SANDHYA, is the issue still open? I will add the review section to the home page while maintaining the beauty and liveliness of the site. Please assign the task to me if that works. Will be happy to help :)

Also, mention the deadline for the issue, in case I am assigned for the same.

**Comment by 2024-SANDHYA** [comment]
@Sanjanabharadwaj25  Please give me an update on this issue, it's already been almost 2 weeks. If you don't want to work on this anymore or don't respond within 24hrs, I'll be assigning  this to @tiasaxena

**Comment by Sanjanabharadwaj25** [comment]
I am working on the issue. I think I will be done with it in a couple of days.
