### ISSUE TITLE
improve Donate Page CSS

### ISSUE THREAD

**Issue by thepranaygupta** [2024-SANDHYA/Blood-Buddy#74]
Add padding and margin to the donate page box, steps and text-box.

## Before:
https://user-images.githubusercontent.com/64855541/146637357-9b8074c9-c236-4025-a7b5-f667d9d40f09.mp4

## After:
https://user-images.githubusercontent.com/64855541/146637366-d4c3e813-79bc-40ed-9ce5-816d891b6a53.mp4

**Comment by prath-10** [comment]
Can you assign me this task?

**Comment by prath-10** [comment]
Can you assign me this task?

**Comment by 4bhishek10** [comment]
can you pls clearify
