### ISSUE TITLE
Scroll Effects

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#76]
You can add a scroll effect on the navbar. Currently when you scroll navbar remains static. You can make it dynamic but adding bg change on a scroll or any other scroll effect.

**Comment by maheshtamarakar** [comment]
is it ok if I make the logo small and in scroll effect change the background color and make the navbar sticky?

**Comment by Jashwanth-k** [comment]
can you assign it to me i was willing to work
