### ISSUE TITLE
Adding footer to Donate Page

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#8]

**Comment by PuneetDabral** [comment]
which kind of footer you need?

**Comment by Mukta-Sawant** [comment]
@2024-SANDHYA Can I work on this as a part of SWOC 21?

**Comment by A-man-404** [comment]
I would love to add a footer to your donate page
Please describe some information about the type of footer you need and also what are the various elements you need in it. 
I've worked with HTML, CSS and JS in the past and if you'll assign it to me, I'd be happy to work on it.
