### ISSUE TITLE
Resize the logo

### ISSUE THREAD

**Issue by 2024-SANDHYA** [2024-SANDHYA/Blood-Buddy#91]
Currently logo is this huge,

![image](https://user-images.githubusercontent.com/75671152/147308234-bb916f01-1793-451d-8941-ac5e945322f1.png)

Change the size and add a hover effect on the logo.

**Comment by greyjedi7** [comment]
Hi Sandhya,

Can you assign this issue to me?

**Comment by 2024-SANDHYA** [comment]
> Hi Sandhya,
> 
> Can you assign this issue to me?

Sure @greyjedi7

**Comment by greyjedi7** [comment]
> > Hi Sandhya,
> > Can you assign this issue to me?
> 
> Sure @greyjedi7

Great. Thanks :)

**Comment by greyjedi7** [comment]
@2024-SANDHYA , I've made the changes. Kindly review it. If you need changes in the color or hover effect, let me know
